services:
  mariadb:
    image: mariadb:10
    container_name: blog-db
    env_file:
      - ./db/.env
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    restart: always
    ports:
      - '13306:3306'
