version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=tst
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -uuser -ptest
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
